# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(SplashScreen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadingLabel = QtWidgets.QLabel(SplashScreen)
        self.loadingLabel.setObjectName("loadingLabel")
        self.verticalLayout.addWidget(self.loadingLabel)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "Splash Screen"))
        self.loadingLabel.setText(_translate("SplashScreen", "Loading, please wait..."))

