# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_ui/chat_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWidget(object):
    def setupUi(self, ChatWidget):
        ChatWidget.setObjectName("ChatWidget")
        ChatWidget.resize(355, 534)
        ChatWidget.setToolTip("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ChatWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conversationTextEdit = QtWidgets.QTextEdit(ChatWidget)
        self.conversationTextEdit.setToolTip("")
        self.conversationTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conversationTextEdit.setObjectName("conversationTextEdit")
        self.verticalLayout.addWidget(self.conversationTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recordingComboBox = QtWidgets.QComboBox(ChatWidget)
        self.recordingComboBox.setMinimumSize(QtCore.QSize(110, 31))
        self.recordingComboBox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.recordingComboBox.setObjectName("recordingComboBox")
        self.recordingComboBox.addItem("")
        self.recordingComboBox.addItem("")
        self.recordingComboBox.addItem("")
        self.recordingComboBox.addItem("")
        self.recordingComboBox.addItem("")
        self.horizontalLayout.addWidget(self.recordingComboBox)
        self.messageIineEdit = QtWidgets.QLineEdit(ChatWidget)
        self.messageIineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.messageIineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.messageIineEdit.setObjectName("messageIineEdit")
        self.horizontalLayout.addWidget(self.messageIineEdit)
        self.messageButton = QtWidgets.QPushButton(ChatWidget)
        self.messageButton.setMinimumSize(QtCore.QSize(31, 31))
        self.messageButton.setMaximumSize(QtCore.QSize(31, 31))
        self.messageButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pyqt5_ui\\data/images/icons/send.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.messageButton.setIcon(icon)
        self.messageButton.setObjectName("messageButton")
        self.horizontalLayout.addWidget(self.messageButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ChatWidget)
        QtCore.QMetaObject.connectSlotsByName(ChatWidget)

    def retranslateUi(self, ChatWidget):
        _translate = QtCore.QCoreApplication.translate
        ChatWidget.setWindowTitle(_translate("ChatWidget", "ASAM System - Chat Panel"))
        self.recordingComboBox.setToolTip(_translate("ChatWidget", "Select Recording"))
        self.recordingComboBox.setItemText(0, _translate("ChatWidget", "None"))
        self.recordingComboBox.setItemText(1, _translate("ChatWidget", "Current"))
        self.recordingComboBox.setItemText(2, _translate("ChatWidget", "Recording 1"))
        self.recordingComboBox.setItemText(3, _translate("ChatWidget", "Recording 2"))
        self.recordingComboBox.setItemText(4, _translate("ChatWidget", "Recording 3"))
        self.messageIineEdit.setPlaceholderText(_translate("ChatWidget", "Message..."))
        self.messageButton.setToolTip(_translate("ChatWidget", "Send Message"))
