# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_ui/video_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoWidget(object):
    def setupUi(self, VideoWidget):
        VideoWidget.setObjectName("VideoWidget")
        VideoWidget.resize(476, 355)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pyqt5_ui\\../data/images/icons/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VideoWidget.setWindowIcon(icon)
        VideoWidget.setToolTip("")
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraGraphicsView = QtWidgets.QGraphicsView(VideoWidget)
        self.cameraGraphicsView.setAutoFillBackground(False)
        self.cameraGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cameraGraphicsView.setLineWidth(1)
        self.cameraGraphicsView.setObjectName("cameraGraphicsView")
        self.verticalLayout.addWidget(self.cameraGraphicsView)

        self.retranslateUi(VideoWidget)
        QtCore.QMetaObject.connectSlotsByName(VideoWidget)

    def retranslateUi(self, VideoWidget):
        _translate = QtCore.QCoreApplication.translate
        VideoWidget.setWindowTitle(_translate("VideoWidget", "ASAM System - Video Panel"))
